# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Australian honey bee colony loss survey"                                # Your name
  description: "Dummy page for the Australian honey bee colony loss survey"   # A brief slogan (optional)
  image: img/my_image.jpg
  
  favicon: img/favicon.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/logo.png
    
    # your sub-pages
    left:
      - text: "Take the survey!"
        href: "https://survey.landcareresearch.co.nz/jfe/form/SV_0cQvadN6lpDiHfo"
    
    # your social media handles
    right:

      - icon: twitter
        href: https://x.com/sashamikheyev
      - icon: envelope
        aria-label: email
        href: "mailto:alexander.mikheyev@anu.edu.au"  
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2024 Australian Colony Loss Survey CC BY-SA 4.0</span>
    center: |
      <span class="faux-block"><a href="https://survey.landcareresearch.co.nz/jfe/form/SV_0cQvadN6lpDiHfo">Take the survet!</a></span>
    right: |
      <span class="faux-block"><a href="https://github.com/mikheyevlab/coloss">View source on GitHub</a></span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true